### ISSUE TITLE
Streaming smaller amounts of data per call?

### ISSUE THREAD

**Issue by perlun** [irmen/pylibxmplite#1]
Hi,

Thanks for an interesting library. :grin: Trying to use to build a simple RPi-based mod visualizer (turning LEDs on and off based on the music being played). This actually works fine, but it feels like the LEDs are "slower" than what they ought to be. I've used the `examples/modplay.py` as basis for my endeavour.

The following code:

```python
def stream_module(xmp: libxmplite.Xmp, display: Display):
    required_frames = yield b""  # generator initialization
    try:
        while True:
            buffer = xmp.play_buffer(required_frames * 2 * 2)
            display.update(xmp.frame_info())
            required_frames = yield buffer

            # Too slow to be usable
            #frame = xmp.play_frame()
            #display.update(xmp.frame_info())
            #yield frame.buffer
    except libxmplite.XmpError as x:
        print("XMP Playback error!!", x)
```

...means that `required_frames` will have a value of 8820 in my example.

I tried to use smaller values there in the `play_buffer` call, but get music stuttering (I guess is expected and the buffer needs to match the sample rate being used?). The "single-frame" based example above also is too slow to be practically usable; I guess you _have to_ use buffering (with a reasonably sized buffer) to get anything sensible out of it.

Any suggestions? I guess Python is not the most performant language in the world for performing real-time computing as well, of course... :slightly_smiling_face: It's just easy with the GPIO handling, I already had a working example of that part which I could base my code on.

Thanks in advance. :pray:

**Comment by perlun** [comment]
Also another problem @irmen - I am having trouble with [modplay-gui.py](https://github.com/irmen/pylibxmplite/blob/master/examples/modplay-gui.py); it hangs whenever I load a module. :thinking: [modplay.py](https://github.com/irmen/pylibxmplite/blob/master/examples/modplay.py) works flawlessly, which surprises me, since the actual mod playback code seems pretty much identical:

https://github.com/irmen/pylibxmplite/blob/8c79b939c9e9ad7a07fe9cb64e68158b32908974/examples/modplay.py#L37-L45

https://github.com/irmen/pylibxmplite/blob/8c79b939c9e9ad7a07fe9cb64e68158b32908974/examples/modplay-gui.py#L150-L158

This is on Debian GNU/Linux (bookworm). Other audio-related programs work fine, and as noted, even `modplay.py` works fine. :slightly_smiling_face:

**Comment by irmen** [comment]
Does it hang or do you get the following error 
  File "/opt/pypy3/lib/pypy3.9/_tkinter/app.py", line 313, in call
    raise NotImplementedError("Call from another thread")
NotImplementedError: Call from another thread

It seems that the gui application no longer works with Python 3.9 or newer. I'll see if this can easily be fixed.

Regarding the amount of data streamed in each iteration, this is decided on by the underlying audio driver, which sits below the pyminiaudio library. You can somewhat control its behavior by setting a different `buffersize_msec` argument to the `miniaudio.PlaybackDevice` construction, for instance set it to 20 and on my system the audio data interator works with chunks of 882 bytes each instead.

**Comment by irmen** [comment]
Ok I think I fixed the multithreading issue in the gui player.

**Comment by perlun** [comment]
> Does it hang or do you get the following error File "/opt/pypy3/lib/pypy3.9/_tkinter/app.py", line 313, in call raise NotImplementedError("Call from another thread") NotImplementedError: Call from another thread

It just hangs, in fact. No error, no nothing.

> It seems that the gui application no longer works with Python 3.9 or newer. I'll see if this can easily be fixed.

Ah, that's an interesting observation; I'm actually using Python 3.10. Thanks for the fixes in baf0f31006aa1d2006314608b0dd4aaf8714b18a; they fix the issue nicely for me. :pray: 

> Regarding the amount of data streamed in each iteration, this is decided on by the underlying audio driver, which sits below the pyminiaudio library. You can somewhat control its behavior by setting a different `buffersize_msec` argument to the `miniaudio.PlaybackDevice` construction, for instance set it to 20 and on my system the audio data interator works with chunks of 882 bytes each instead.

This may have been a bit of a "dead end" for me; I moved the GPIO visualization to a separate thread (https://github.com/perlun/modplay/commit/751b83e22d43bdf0af99cacf6c33a3b39d937938), but it didn't do a significant difference. But thanks for these suggestions as well, I saw you included them in that same commit as well. :+1: 

(For reference, in case anyone wants to see my end result: https://github.com/perlun/modplay)

**Comment by irmen** [comment]
@perlun hm, weird, I ninja added those buffer size settings in my commit mentioned above to make the buffer smaller so that the update rate of the GUI increased. It really does work on my end.  (Manjaro Linux with pulseaudio audio backend).   Maybe the audio backend on the RPI doesn't listen to the buffer size suggestion? Very hard to say. 
If you want to pursue that further I suggest looking into programming some code on pyminiaudio directly or even trying the miniaudio C library with their C example code to see if you can tweak things on that level successfully.

**Comment by perlun** [comment]
@irmen Ah, sorry if that last message was a bit confusing:

- The GUI app: before your commit, it would hang completely on my Debian GNU/Linux laptop. With the ninja-commit :joy: it worked like it should. Could perhaps be the Python 3.9+ fix that unbroke it?

- On the RPi, I never tried modifying the buffer settings. I changed my code (before your fix) to run the GPIO stuff on a separate thread with a minimal delay between each polling of the `xmp.frame_info()` data: `sleep(0.001)`(https://github.com/perlun/modplay/blob/751b83e22d43bdf0af99cacf6c33a3b39d937938/modplay.py#L75)

However, even with this change in place, it still wasn't as "fast" in updating the GPIO LEDs as I expected it to be, so I think the issue was more with my expectations than with the software. :slightly_smiling_face: I also looked on some of the `.mod` files I was working with and at least one of them had notes being played on _every line_ in the pattern. So obviously this wouldn't be much "blinking" in that case, more like a steady light.

Does this make sense? :thinking: Here's what it looked like for me (I think I used `sleep(0.05)` when I recorded that video): https://www.youtube.com/watch?v=3TEI_KRq3IY

**Comment by irmen** [comment]
@perlun 
Ok I understand everything you're seeing now I think.

Still if the leds are updated from within the audio frame callback generator, having a large buffer size will call the update routine less frequently. This is why I ninja-changed the buffer size parameter to something smaller in the gui player as well.  It was updating very slowly at first.  You can set it even lower to make the bars update even faster.   I think the leds will blink more naturally on the Rpi as well if you lower the playback device buffer size.
